inherit_from: configs/ScanNet/scannet.yaml

mapping:
  bound: [ [1.3, 7.8], [-0.3, 8.5], [-0.3, 2.9] ]
  marching_cubes_bound: [ [1.3, 7.8], [-0.3, 8.5], [-0.3, 2.9] ]

data:
  datadir: /home/hanwen/data/ScanNet/scans/scene0011_00/frames
  trainskip: 1
  output: output/scannet/scene0011_00
  exp_name: "0"
  starting_frame: -1

tracking:
  iter_RO: 0
  iter: 10
  switch_interval: 90
  switch:
    align_threshold: 0.1

cam:
  near: 0
  far: 7

