inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.3, 9.6],[-0.3, 9.4],[-0.3, 3.5]]
  marching_cubes_bound: [[-0.3, 9.6],[-0.3, 9.4],[-0.3, 3.5]]

data:
  datadir: /home/hanwen/data/ScanNet/scans/scene0106_00/frames
  trainskip: 1
  output: output/scannet/scene0106_00
  exp_name: "0"
  starting_frame: -1

tracking:
  iter_RO: 0
  iter: 10