inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [ [ 0.5, 9.1 ],[ -0.3, 7.8 ],[ -0.3, 2.7 ] ]
  marching_cubes_bound: [ [ 0.5, 9.1 ],[ -0.3, 7.8 ],[ -0.3, 2.7 ] ]
  localMLP_max_len: [6., 6., 4.]

data:
  datadir: /home/hanwen/data/ScanNet/scans/scene0169_00/frames
  trainskip: 1
  output: output/scannet/scene0169_00
  exp_name: "0"
  starting_frame: 0

tracking:
  iter_RO: 0
  iter: 10

cam:
  H: 480
  W: 640
  fx: 574.540771
  fy: 577.583740
  cx: 322.522827
  cy: 238.558853
  near: 0
  far: 7.
